spring.application.name=ecommerce-back

# Puerto del servidor (Usa el puerto que asigne Render o 8081 localmente)
server.port=${PORT:8081}

# Configuración de base de datos PostgreSQL 
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
